### ISSUE TITLE
 disable the duty circle.

### ISSUE THREAD

**Issue by chrisj8727** [ivesdebruycker/maxcube#10]
it is possible to disable the duty circle.
This is annoying especially during testing.
thanks in advance chris

**Comment by ivesdebruycker** [comment]
As far as I know, that's not possible. See also the answers by others on the same question you asked in other repos: 
- https://github.com/autopower/thermeq3/issues/8
- https://github.com/Bouni/max-cube-protocol/issues/24
- https://github.com/ivesdebruycker/node-red-contrib-maxcube/issues/3
- https://github.com/ivesdebruycker/maxcube-cli/issues/1
- https://github.com/ivesdebruycker/maxcube/issues/10
