### ISSUE TITLE
Problem: Setting mode/temperature for rooms with wall thermostat not working

### ISSUE THREAD

**Issue by jwildeboer** [ivesdebruycker/maxcube#14]
The MAX! system allows different setups. The simple setup of directly managed thermostats (Device Type 1) works.

But when you introduce a wall thermostat/display unit (device Type 3) the model changes to "room setup" which is not yet supported in maxcube.

In my livingroom I have two thermostats controlled by one wall thermostat. In that setup any command to set temperature or mode on the thermostats directly fails. Sending temperature/mode commands to the rf_address of the wall thermostat (device type 3) also fails with

`Dec 07 19:23:10 rpi.home.lan nodered[2587]: 7 Dec 19:23:10 - [info] [maxcube in:4116adfa.b3ac54] Error setting temperature`

I am not sure how this is supposed to work (IIRC it means sending temperature/mode commands to the room_id and not to the thermostats or wall device) but I am looking a bit deeper into this.

**Comment by jwildeboer** [comment]
Solution: Treat wall thermostat as normal thermostat. Implemented in PR #15 Tested with 2 wall thermostats. Setting mode and temperature works as expected.

**Comment by ivesdebruycker** [comment]
Great, thanks for your work.
