### ISSUE TITLE
current temperature not shown only on wall thermostats

### ISSUE THREAD

**Issue by strandbein** [ivesdebruycker/maxcube#27]
Hello,

I’m using https://www.npmjs.com/package/homebridge-platform-maxcube on Raspberry Pi 3. All is running fine, only one small thing doesn’t work: the temperature of the wall thermostats is always showing 0 degrees. With radiator thermostats everything works perfectly.
The developer of platform-maxcube answered me:
I have no idea, also no way to test it as I have no wall thermostats. If its a software issue then most probably its with the underlying library we use to access the thermostats, so outside the scope of this project: https://github.com/DanielWeeber/maxcube-window

And no my question:
Is it possible to correct this with reasonable effort?
Thank you.

**Comment by DanielWeeber** [comment]
I also have no Wall Thermostat, so I cannot check it. My repo only adds the compatibility for Window Switches.
The Wall Thermostat uses the same functions as the Wall Thermostat, maybe they differ. Not very likely, but possible.

**Comment by ivesdebruycker** [comment]
The temperature of the wall thermostats should now be fixed after merging #25. Could you test this?

**Comment by olli1705** [comment]
tested the fix before you merged it. did not work for me...

**Comment by ivesdebruycker** [comment]
@olli1705, could you try the debug branch? It has some verbose logging to help fix the issue. Please post your log here

**Comment by JanScheeleDev** [comment]
I had a problem too and found out, that the wallmount is using different bytes for temp-values. I fixed it by modifying maxcube-commandparser.js:298:

`        if (deviceType == EQ3MAX_DEV_TYPE_WALLTHERMOSTAT) {
            deviceStatus.temp = (payload[8]>=128 ? 25.5 : 0) + payload[12] / 10;
        } else {
            deviceStatus.temp = (payload[20]>=128 ? 25.5 : 0) + payload[24] / 10;
        }
`
[decoded_254.txt](https://github.com/ivesdebruycker/maxcube/files/2303713/decoded_254.txt)
[decoded_275.txt](https://github.com/ivesdebruycker/maxcube/files/2303714/decoded_275.txt)
[decoded_280.txt](https://github.com/ivesdebruycker/maxcube/files/2303715/decoded_280.txt)
[decoded_340.txt](https://github.com/ivesdebruycker/maxcube/files/2303716/decoded_340.txt)

Edit: I had to correct the condition to only pick up on the 1st bit. I got strange results.

**Comment by maxill1** [comment]
The fix I made (https://github.com/ivesdebruycker/maxcube/pull/25) is working for my wallmounted thermostat and i tried to implement what is documented here 
https://github.com/Bouni/max-cube-protocol/blob/master/L-Message.md#actual-temperature-wallmountedthermostat and here https://github.com/Bouni/max-cube-protocol/pull/34/commits/2993488431a60782ba15ada1c6bdd46a8c20402f

**I personally tried all your fixes** and the only one that works (partially) for me is Sylas007's but it lacks on setpoint, all the others give me bad readings:

-  setpoint 81 (should be 17) 
-  temp 2.2 (should be 27.8)

`{
    "rf_address": "18eb18",
    "initialized": true,
    "fromCmd": false,
    "error": false,
    "valid": true,
    "mode": "AUTO",
    "dst_active": true,
    "gateway_known": true,
    "panel_locked": false,
    "link_error": false,
    "battery_low": false,
    "valve": 4,
    "setpoint": 81,
    "temp": 2.2,
    "device_type": 3,
    "device_name": "Termostato a parete",
    "room_name": "Piano terra",
    "room_id": 1
}`


I tried to dig into issues and found out that for some of us the wall thermostats can be parsed like a valve thermostat and for some it's like described on Bouni's max-cube-protocol page:
jwildeboer: https://github.com/ivesdebruycker/maxcube/pull/15
pawelwiecaszek: https://github.com/ivesdebruycker/maxcube/pull/24
sylas007: https://github.com/Bouni/max-cube-protocol/issues/43 and here (https://github.com/ivesdebruycker/maxcube/issues/27).
normen: https://github.com/normen/maxcube2/commit/b2a8555297e25a1e2d42add2a22c6a967325ddb5

**This fragmentation makes me wonder if there are two different version for the wallmounted thermostat or cube firmare that reports differently.**

I read somewhere that may exist a "plus" version and a "standard" version just like valve thermostats but can't find any evidence on EQ3 site.

Mine is a eQ-3 AG 131651 A0, also referenced as BC-TC-C-WM-4 in EQ3 manuals, EAN code 4047976316519 and serial OEQ0812745.

You can find online a some wall thermostat with different model number: eQ-3 105936 or 105679 with EAN code 4047976116515

However i'm using this function now and seems to read fine (aa2bf2ace1cceeda6a4460da45d1174c79b43eef):
```
  deviceStatus.setpoint = (63 & payload[8]) / 2;
  deviceStatus.temp = (payload[8]>=128 ? 25.5 : 0) + payload[12] / 10;
```

Edit: additional info https://www.domoticaforum.eu/viewtopic.php?f=66&t=6654&start=120#p73018
